version: '3.8'

services:
    my-app1:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - my-network

    my-app2:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - my-network

    nginx:
        image: nginx:latest
        ports:
            - "80:80"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./.htpasswd:/etc/nginx/.htpasswd:ro
        depends_on:
            - my-app1
            - my-app2
        networks:
            - my-network

networks:
    my-network:
        driver: bridge
