version: '3.8'

services:
    my-app1:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - my-network
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    cpus: "0.7"
                    memory: "225MB"

    my-app2:
        build:
            context: .
            dockerfile: Dockerfile
        networks:
            - my-network
        depends_on:
            - db
        deploy:
            resources:
                limits:
                    cpus: "0.7"
                    memory: "225MB"

    nginx:
        image: nginx:latest
        ports:
            - "9999:9999"
        volumes:
            - ./nginx.conf:/etc/nginx/nginx.conf:ro
            - ./.htpasswd:/etc/nginx/.htpasswd:ro
        depends_on:
            - my-app1
            - my-app2
        networks:
            - my-network
        deploy:
            resources:
                limits:
                    cpus: "0.05"
                    memory: "10MB"

    db:
        image: postgres:latest
        hostname: db
        environment:
            - POSTGRES_PASSWORD=123
            - POSTGRES_USER=admin
            - POSTGRES_DB=rinha
        ports:
            - "5432:5432"
        volumes:
            - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
        command: postgres -c checkpoint_timeout=600 -c max_wal_size=4096
        networks:
            - my-network
        deploy:
            resources:
                limits:
                    cpus: "0.05"
                    memory: "90MB"

networks:
    my-network:
        driver: bridge
