name: build-with-maven
on:
    workflow_dispatch:
    push:
        branches: ["master"]
        paths-ignore:
            - k8s/*

jobs:
    generate-jar:
        runs-on: ubuntu-latest
        container:
            image: maven:3.8.7-openjdk-18-slim
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: 17
                  cache: 'maven'

            - name: Build with Maven
              run: mvn -B clean package -Dunit.skip=true --file pom.xml


    unit-test:
        needs: generate-jar
        runs-on: ubuntu-latest
        container:
            image: maven:3.8.7-openjdk-18-slim
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: '17'
                    cache: 'maven'
            -   name: Unit Tests
                run: mvn clean -B test
    
    push-to-hub:
        needs: unit-test
        runs-on: ubuntu-latest
        steps:
        - name: Checkout do código conte
          uses: actions/checkout@v4.1.7

        - name: Login no Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
          
        - name: Build and push
          uses: docker/build-push-action@v6.2.0
          with:
            context: ./
            push: true
            file: ./Dockerfile
            tags: |
                vandeilsonln/nginx-study:v${{ github.run_number }}
                vandeilsonln/nginx-study:latest

    deploy:
        needs: push-to-hub
        uses: ./.github/workflows/deploy.yaml
