name: build-with-maven
on:
    workflow_dispatch:
    pull_request:
        branches: [master]
    push:
        branches:
            - main

jobs:
    generate-jar:
        runs-on: ubuntu-latest
        container:
            image: maven:3.8.7-openjdk-18-slim
        steps:
            - uses: actions/checkout@v3
            - uses: actions/setup-java@v3
              with:
                  distribution: 'zulu'
                  java-version: 17
                  cache: 'maven'

            - name: Build with Maven
              #run: mvn -B clean package -Dunit.skip=true --file pom.xml
              run: echo "Mock para evitar demorar"


    unit-test:
        needs: generate-jar
        runs-on: ubuntu-latest
        container:
            image: maven:3.8.7-openjdk-18-slim
        steps:
            -   uses: actions/checkout@v3
            -   uses: actions/setup-java@v3
                with:
                    distribution: 'zulu'
                    java-version: '17'
                    cache: 'maven'
            -   name: Unit Tests
                #run: mvn clean -B test
                run: echo "mock para evitar de demorar"

    deploy:
        needs: [unit-test]
        uses: ./.github/workflows/deploy.yaml
        secrets:
            DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
            DOCKER_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
            AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
            AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
