name: deployment
on:
  workflow_call:

jobs:
  CD:
    runs-on: ubuntu-latest
    steps:
      - name: Obtendo o código
        uses: actions/checkout@v3
        
      - name: GitOps
        run: |
          git config --global user.name "Vandeilson Nobre"
          git config --global user.email "vandernobrel@gmail.com"
          sed -i 's/image: vandeilsonln\/nginx-study:v[0-9]\{1,3\}/image: vandeilsonln\/nsingx-study:v${{github.run_number}}/' ./k8s/deployment.yaml
          git add .
          git commit -m "new tag - ${{github.run_number}}"
          git push origin
      # - name: Configure AWS Credentials
      #   uses: aws-actions/configure-aws-credentials@v4
      #   with:
      #     aws-access-key-id: secrets.AWS_ACCESS_KEY_ID
      #     aws-secret-access-key: secrets.AWS_SECRET_ACCESS_KEY 
      #     aws-region: us-east-1

      # - name: Configure Kubeconfig
      #   run: aws eks update-kubeconfig --name cluster-study

      # - name: Deploy to k8s
      #   uses: Azure/k8s-deploy@v5.0.0
      #   with:
      #    manifests: |
      #      ./k8s/deployment.yaml
      #    images: |
      #      vandeilsonln/nginx-study:v github.run_number
    
